### ISSUE TITLE
DockerBuildError

### ISSUE THREAD

**Issue by KaiserW** [ibleducation/jupyter-edx-grader-xblock#6]
I followed the README and completed the installation/configuration, but faced this error when uploading instructor notebook:

```
2018-08-09 14:17:25,862 ERROR 31272 [xblock_jupyter_graded.xblock_jupyter_graded] xblock_jupyter_graded.py:264 -
Traceback (most recent call last):
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/xblock_jupyter_graded/xblock_jupyter_graded.py", line 244, in handle_instructor_nb_upload
    str(self.course_id), str(self.location), f)
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/xblock_jupyter_graded/nbgrader_utils.py", line 54, in generate_student_nb
    max_score = _run_assign_container(f.filename, course, unit)
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/xblock_jupyter_graded/nbgrader_utils.py", line 79, in _run_assign_container
    build_container_if_not_exists(course_id)
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/xblock_jupyter_graded/nbgrader_utils.py", line 213, in build_container_if_not_exists
    manager.build_container()
  File "/opt/openedx/venv/local/lib/python2.7/site-packages/xblock_jupyter_graded/container_manager.py", line 134, in build_container
    raise DockerBuildError(out.decode('utf-8'))
DockerBuildError
```

---

OS: Ubuntu 16.04 x64
OpenEdx version: Ginkgo

**Comment by labarba** [comment]
Your docker image didn't build. Did you upload a `requirements.txt` file?

**Comment by mamigot** [comment]
Closing for now, @KaiserW , but feel free to reopen!
